#!/bin/bash

echo "walic orka"
zmienna=""
echo "podaj nazwe pliku"
read file_path
nazwaplik=file_pat
if [ ! -n  $file_path ]
then
echo "ten plik nie istnieje"
else
echo "ten plik istnieje"
fi
if [ -z  $file_path ]
then
echo "ten plik jest pusty"
fi
echo "co mam zrobic? wypisz literkeee"
echo "a - dodanie zadania"
echo "b - usuniecie ostatniego zada "
echo "c - znalezienie zadania"
echo "d - wypisz wszystkich zadan"
read file_path
zadanie=file_path
if [ zadanie = "a"]
then
echo "t"
fi
if [ zadanie = "b"]
then
${!#}
echo "t"
fi
if [ zadanie = "c"]
then
echo "t"
fi
if [ zadanie = "d"]
then
echo "t"
fi